### ISSUE TITLE
High FPS Physics Fix Crash

### ISSUE THREAD

**Issue by nolyd3** [themidnightride/themidnightride.github.io#1]
The line mentioned in the guide DisableBlackLoadingScreens=true is crashing the game during character generation. Specifically within the Blemishes section when disabling/enabling. 

[crash-2021-02-25-10-19-36.log](https://github.com/themidnightride/themidnightride.github.io/files/6042329/crash-2021-02-25-10-19-36.log)

Returning both 
DisableBlackLoadingScreens
DisableAnimationOnLoadingScreens

To false solved the issue.

**Comment by TDarkShadow** [comment]
Could you copy and paste your crash log, ModOrganizer2\Fallout4\profiles\TheMidnightRide modlist.txt and loadorder.txt to either [Github Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/) please?

**Comment by nolyd3** [comment]
[Crash Log](https://pastebin.com/GnHzg54S)

[Mod List](https://pastebin.com/8CHEJJJG)

[Load Order](https://pastebin.com/tPvpxccp)

**Comment by TDarkShadow** [comment]
I'm thinking this might an AMD cpu issue.
Which is something neither Qolore nor me can test at this moment.

**Comment by nolyd3** [comment]
I think you may be right. I booted another Intel based rig and the same mod list. No crashes.
