### ISSUE TITLE
Invalid settings in Fallout4Custom.ini

### ISSUE THREAD

**Issue by OnmyojiOmn** [themidnightride/themidnightride.github.io#4]
Your recommended settings include a bunch of stuff that's normally set in Fallout4Prefs.ini, namely all of the shadow settings as well as bMBEnable. It seems that Fallout4Custom.ini can only override settings from Fallout4.ini because reasons, so these aren't applied in-game.

**Comment by VivaNewVegas** [comment]
Lmao sorry I didn't respond to this for like a month, but I did finally fix it a bit ago! Thank you for the heads up
